CREATE DATABASE IF NOT EXISTS chefbook;
USE chefbook;

CREATE TABLE IF NOT EXISTS accounts (
    username  VARCHAR(50)  NOT NULL PRIMARY KEY,
    password  VARCHAR(255) NOT NULL,
    name      VARCHAR(100) NOT NULL,
    email     VARCHAR(100) NOT NULL UNIQUE
);